// Generates the Flutter palette from frontend CSS. Usage: node tool/sync_design_tokens.mjs [globals.css] [--check]
import fs from 'node:fs';
import crypto from 'node:crypto';
const source = process.argv.find((v, i) => i > 1 && !v.startsWith('--')) ?? '../video-server/frontend/src/app/globals.css';
const css = fs.readFileSync(source, 'utf8');
const channels = (l, c, h) => {
  const a = c * Math.cos(h * Math.PI / 180), b = c * Math.sin(h * Math.PI / 180);
  const ll = (l + .3963377774 * a + .2158037573 * b) ** 3;
  const m = (l - .1055613458 * a - .0638541728 * b) ** 3;
  const s = (l - .0894841775 * a - 1.291485548 * b) ** 3;
  return [4.0767416621 * ll - 3.3077115913 * m + .2309699292 * s,
    -1.2684380046 * ll + 2.6097574011 * m - .3413193965 * s,
    -.0041960863 * ll - .7034186147 * m + 1.707614701 * s].map(v => Math.round(Math.min(1, Math.max(0, v <= .0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - .055)) * 255));
};
const hex = v => v.toString(16).padStart(2, '0').toUpperCase();
const blocks = [':root', '.dark'].map(selector => {
  const start = css.indexOf(`${selector} {`);
  const body = css.slice(start, css.indexOf('}', start));
  return Object.fromEntries([...body.matchAll(/--([\w-]+):\s*([^;]+);/g)].map(([, k, v]) => [k, v]));
});
const names = ['background', 'foreground', 'card', 'card-foreground', 'popover', 'popover-foreground', 'primary', 'primary-foreground', 'secondary', 'secondary-foreground', 'muted', 'muted-foreground', 'accent', 'accent-foreground', 'destructive', 'border', 'input', 'ring', 'success', 'warning'];
const palettes = blocks.map((block, i) => `const ${i ? 'dark' : 'light'}WebColors = <String, Color>{\n${names.map(name => {
  const value = block[name];
  const match = /^oklch\(([\d.]+) ([\d.]+) ([\d.]+)(?: \/ ([\d.]+)(%)?)?\)$/.exec(value);
  if (!match) throw new Error(`Unsupported color ${name}: ${value}`);
  const [, l, c, h, alpha, percent] = match;
  const aa = alpha === undefined ? 255 : Math.round(Number(alpha) / (percent ? 100 : 1) * 255);
  return `  '${name}': Color(0x${[aa, ...channels(+l, +c, +h)].map(hex).join('')}),`;
}).join('\n')}\n};`);
const radius = /^([\d.]+)rem$/.exec(blocks[0].radius);
if (!radius) throw new Error(`Unsupported radius: ${blocks[0].radius}`);
const radiusPixels = Number(radius[1]) * 16;
const dartRadius = Number.isInteger(radiusPixels) ? radiusPixels.toFixed(1) : String(radiusPixels);
const output = `// GENERATED by tool/sync_design_tokens.mjs. Do not edit.\n// Source CSS SHA256: ${crypto.createHash('sha256').update(css).digest('hex')}\nimport 'package:flutter/painting.dart';\n\nconst webRadius = ${dartRadius};\n\n${palettes.join('\n\n')}\n`;
const target = 'lib/core/theme/web_colors.g.dart';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8') !== output) throw new Error('Web theme changed. Regenerate and review App tokens.');
} else fs.writeFileSync(target, output);
