// GENERATED by tool/sync_design_tokens.mjs. Do not edit.
// Source CSS SHA256: 1d4bc2dea17feb4a44e80444ae62648a19bdb8593b4343b7bc669c77940209de
import 'package:flutter/painting.dart';

const webRadius = 10.0;

const lightWebColors = <String, Color>{
  'background': Color(0xFFFFFFFF),
  'foreground': Color(0xFF0A0A0A),
  'card': Color(0xFFFFFFFF),
  'card-foreground': Color(0xFF0A0A0A),
  'popover': Color(0xFFFFFFFF),
  'popover-foreground': Color(0xFF0A0A0A),
  'primary': Color(0xFF171717),
  'primary-foreground': Color(0xFFFAFAFA),
  'secondary': Color(0xFFF5F5F5),
  'secondary-foreground': Color(0xFF171717),
  'muted': Color(0xFFF5F5F5),
  'muted-foreground': Color(0xFF737373),
  'accent': Color(0xFFF5F5F5),
  'accent-foreground': Color(0xFF171717),
  'destructive': Color(0xFFE7000B),
  'border': Color(0xFFE5E5E5),
  'input': Color(0xFFE5E5E5),
  'ring': Color(0xFFA1A1A1),
  'success': Color(0xFF00793D),
  'warning': Color(0xFF915200),
};

const darkWebColors = <String, Color>{
  'background': Color(0xFF0A0A0A),
  'foreground': Color(0xFFFAFAFA),
  'card': Color(0xFF171717),
  'card-foreground': Color(0xFFFAFAFA),
  'popover': Color(0xFF171717),
  'popover-foreground': Color(0xFFFAFAFA),
  'primary': Color(0xFFE5E5E5),
  'primary-foreground': Color(0xFF171717),
  'secondary': Color(0xFF262626),
  'secondary-foreground': Color(0xFFFAFAFA),
  'muted': Color(0xFF262626),
  'muted-foreground': Color(0xFFA1A1A1),
  'accent': Color(0xFF262626),
  'accent-foreground': Color(0xFFFAFAFA),
  'destructive': Color(0xFFFF6467),
  'border': Color(0x1AFFFFFF),
  'input': Color(0x26FFFFFF),
  'ring': Color(0xFF737373),
  'success': Color(0xFF33CC7D),
  'warning': Color(0xFFF0B135),
};
